#!/usr/bin/env python3
"""sitebase.py — the shared site-drawing base for the Arcado Springs sheet set.

This module is NOT a sheet generator. It is imported by the site sheets
(C-0 Existing Conditions, and later L-1 Landscape/Buffer, C-3 Grading and Drainage,
C-4 Utility and Phasing) so that every one of them draws the same site, in the same
site-local (u, v) coordinate system, at the same scale, inside the same ARCH D title
block.

COORDINATE SYSTEM (FACTS.md section 1)
    origin  = the Arcado Rd right-of-way corner shared by parcel R6123 162 and the R/W
              (SR 2240 GA West US survey ft: 2,310,954.00 E / 1,411,431.50 N)
    +u      = along the strip, bearing N 28 deg 43' W, from Arcado Rd toward the NW end
              (u runs -36 ft at the R/W to 1,722 ft at the rear line)
    +v      = across the strip toward the NE line; negative toward the SW line
              (v runs -237.5 to +9)
    Grid north therefore lies 28 deg 43' (28.72 deg) counter-clockwise from the +u axis;
    north_arrow() draws it at that angle.

DRAWING CONVENTIONS
    Taken from tools/siteplan.py (Sheet C-1, the master concept plan) so that C-0 and
    C-1 overlay each other exactly: ARCH D 36 x 24 in, 1" = 60' (1.2 pt/ft) in the plan
    window WIN, plan origin at (102, 52) sheet points, the same colour palette, the same
    hatch definitions, the same Drawing/Labeler/table() primitives and the same title
    block. The ARCH C title-block wording of tools/elevations.py _sheet_frame() (project
    line, address line, status line, disclaimer, marker) is carried over as well.

WHY THIS MODULE DOES NOT `import siteplan`
    tools/siteplan.py builds the whole proposed layout at IMPORT time and, as a
    module-level side effect, REWRITES data/layout.json (line "json.dump(LAYOUT, ...)").
    A sheet generator that imported it would silently regenerate another agent's data
    file every time it ran, and would fail whenever siteplan.py is mid-edit. sitebase
    therefore reads the JSON that siteplan.py produces and reuses its conventions
    explicitly; the two files must be kept in step by hand if the palette changes.
    tools/floorplans.py has no import-time side effects, so render_png() and the
    canonical DISCLAIMER / MARKER strings ARE imported from it.

WHAT IS IN HERE
    sheet(title, sheet_no, subtitle, scale_note)     -> (Drawing, frame metrics dict)
    finish(D) / save(D, basename)                    -> SVG string / .svg + .png on disk
    enlargement(u0, u1, v0, v1, x, y, scale)         -> a second Drawing at 1" = 30'
    place(D, sub, title=...)                         -> paste an enlargement onto a sheet
    match_lines(c, regions=...)                      -> match-line boxes on the full plan
    boundary, parcel_lines, adjoiners, contours, streams_and_buffers, sewer_existing,
    water_existing, arcado_row, existing_structures, wooded_area,
    lots, lane, amenity, ponds, open_space, north_arrow, scalebar, spot_elevations
    Every layer takes a Drawing as its first argument, so a sheet composes exactly the
    layers it needs and each layer works unchanged in the full-length plan and inside an
    enlargement.

Run `python3 tools/sitebase.py` for a self-check: it loads the data, exercises every
layer on a throw-away canvas and prints the element counts. It writes nothing.

DRAFT — NOT SEALED. All geometry is from the Gwinnett County GIS parcel fabric, the USGS
3DEP DEM and public aerial-imagery footprints; a Georgia RLS boundary and topographic
survey is required and governs.
"""
import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, 'data')
DRAW = os.path.join(ROOT, 'drawings')
sys.path.insert(0, HERE)
import floorplans as fp                                   # noqa: E402  (no import-time side effects)

DISCLAIMER, MARKER = fp.DISCLAIMER, fp.MARKER
DATE = '2026-09-03'


def _load(name):
    with open(os.path.join(DATA, name)) as fh:
        return json.load(fh)


LAYOUT = _load('layout.json')                 # the site layout generated by tools/siteplan.py
CTX = _load('site-context-local.json')        # GIS context in site-local coordinates
TOPO = _load('topo-samples.json')             # USGS 3DEP spot elevations (u, v, lon, lat, z_ft)
ADJOIN_ROSTER = _load('adjoining-parcels.json')   # PIN / address roster for the 31 adjoiners + R/W
OWNERS = _load('owners-found.json')           # Gwinnett 2026 digest owner records by PIN

# ============================================================================ sheet standards
SHEET_W, SHEET_H = 36 * 72, 24 * 72           # ARCH D landscape, points
MARGIN, INNER = 36.0, 6.0
SCALE60 = 72.0 / 60.0                          # 1" = 60'  -> 1.2 pt/ft   (full-length layout)
SCALE30 = 72.0 / 30.0                          # 1" = 30'  -> 2.4 pt/ft   (enlargements)
WIN = (-150.0, 1840.0, -430.0, 240.0)          # plan window u0, u1, v0, v1 (ft) — same as Sheet C-1
PLAN_X0, PLAN_Y0 = 102.0, 52.0                 # plan-window top-left in sheet points
PLAN_W = (WIN[1] - WIN[0]) * SCALE60           # 2388 pt
PLAN_H = (WIN[3] - WIN[2]) * SCALE60           # 804 pt
BAND_Y0 = PLAN_Y0 + PLAN_H + 28                # 884 — top of the data/legend/notes band
TB_H = 112.0
TB_Y = SHEET_H - MARGIN - TB_H                 # 1580 — top of the title block
BAND_Y1 = TB_Y - 50                            # 1530 — bottom of the band (disclaimer strip below)
FONT = "'Liberation Sans', Arial, Helvetica, sans-serif"
NORTH_DEG = 28.72                              # grid north, degrees counter-clockwise from +u

PROJECT = 'THE COTTAGES AT ARCADO SPRINGS'
ADDRESSES = '4535 / 4537 / 4539 / 4541 Arcado Rd SW, Lilburn, GA 30047'
LEGAL = 'Land Lot 123, 6th District, Gwinnett County — PINs R6123 033, 015, 014, 162 — 9.44 ac (deeded)'
APPLICANT = 'Mohammed Awad'

C = {                                          # palette (identical to Sheet C-1 where the layer is shared)
    'bnd': '#000', 'parcel': '#333', 'adj_fill': '#f5f5f2', 'adj_line': '#9a9a9a', 'adj_text': '#444',
    'contour': '#a67c52', 'contour_txt': '#7a5230', 'stream': '#1565c0', 'buf_line': '#1f77b4',
    'sewer': '#2e7d32', 'sewer_txt': '#1b5e20', 'water': '#0277bd', 'hydrant': '#b00',
    'exist': '#8d3b0f', 'exist_fill': '#f0e2d6', 'wood_line': '#3d6b35', 'wood_txt': '#1b5e20',
    'pave': '#d6d6d6', 'tract': '#ececec', 'house': '#f9e4c8', 'green': '#dff0d8', 'green_line': '#5a8a4a',
    'pond': '#cfe3f3', 'phase': '#7b1fa2', 'red': '#b00', 'rw': '#777', 'match': '#c62828',
}

DEFS = '''<defs>
<pattern id="bufhatch" patternUnits="userSpaceOnUse" width="6" height="6" patternTransform="rotate(45)"><line x1="0" y1="0" x2="0" y2="6" stroke="#7a9b5a" stroke-width="0.6"/></pattern>
<pattern id="r2hatch" patternUnits="userSpaceOnUse" width="8" height="8" patternTransform="rotate(-45)"><rect width="8" height="8" fill="#fff3e0"/><line x1="0" y1="0" x2="0" y2="8" stroke="#e0a060" stroke-width="0.6"/></pattern>
<pattern id="woods" patternUnits="userSpaceOnUse" width="26" height="26"><rect width="26" height="26" fill="#f3f8f0"/><circle cx="6" cy="6" r="3.0" fill="none" stroke="#7ea373" stroke-width="0.45"/><circle cx="19" cy="17" r="3.0" fill="none" stroke="#7ea373" stroke-width="0.45"/><circle cx="19" cy="4" r="1.7" fill="none" stroke="#9dbb95" stroke-width="0.35"/><circle cx="6" cy="20" r="1.7" fill="none" stroke="#9dbb95" stroke-width="0.35"/></pattern>
<pattern id="exhatch" patternUnits="userSpaceOnUse" width="5" height="5" patternTransform="rotate(45)"><rect width="5" height="5" fill="#f0e2d6"/><line x1="0" y1="0" x2="0" y2="5" stroke="#8d3b0f" stroke-width="0.55"/></pattern>
<pattern id="ssehatch" patternUnits="userSpaceOnUse" width="7" height="7" patternTransform="rotate(-45)"><line x1="0" y1="0" x2="0" y2="7" stroke="#2e7d32" stroke-width="0.5"/></pattern>
</defs>'''


def esc(t):
    return str(t).replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')


def attrs(kw):
    return ' '.join('%s="%s"' % (k.replace('_', '-'), v) for k, v in kw.items())


def wrap(t, n=20):
    """greedy word wrap to n characters (same helper as tools/siteplan.py)."""
    words, lines, cur = str(t).split(), [], ''
    for w in words:
        if len(cur) + len(w) + 1 > n and cur:
            lines.append(cur)
            cur = w
        else:
            cur = (cur + ' ' + w).strip()
    if cur:
        lines.append(cur)
    return lines or ['']


# ============================================================================ geometry helpers
def dist(a, b):
    return math.hypot(a[0] - b[0], a[1] - b[1])


def poly_area(p):
    return 0.5 * sum(p[i][0] * p[(i + 1) % len(p)][1] - p[(i + 1) % len(p)][0] * p[i][1] for i in range(len(p)))


def poly_centroid(p):
    A = poly_area(p)
    if abs(A) < 1e-9:
        return (sum(q[0] for q in p) / len(p), sum(q[1] for q in p) / len(p))
    cx = cy = 0.0
    for i in range(len(p)):
        x0, y0 = p[i]
        x1, y1 = p[(i + 1) % len(p)]
        f = x0 * y1 - x1 * y0
        cx += (x0 + x1) * f
        cy += (y0 + y1) * f
    return (cx / (6 * A), cy / (6 * A))


def point_in_poly(pt, poly):
    x, y = pt
    inside = False
    n = len(poly)
    for i in range(n):
        x0, y0 = poly[i]
        x1, y1 = poly[(i + 1) % n]
        if (y0 > y) != (y1 > y):
            if x0 + (y - y0) * (x1 - x0) / (y1 - y0) > x:
                inside = not inside
    return inside


def interp_v(path, u):
    """v on a polyline that is monotone in u (linear interpolation, clamped at the ends)."""
    if u <= path[0][0]:
        return path[0][1]
    for i in range(len(path) - 1):
        (u0, v0), (u1, v1) = path[i], path[i + 1]
        if u0 <= u <= u1 and u1 > u0:
            return v0 + (v1 - v0) * (u - u0) / (u1 - u0)
    return path[-1][1]


def rect(u0, u1, v0, v1):
    return [(u0, v0), (u1, v0), (u1, v1), (u0, v1)]


def offset_band(path, half):
    """A closed polygon 'half' feet either side of an open polyline (blunt ends)."""
    left, right = [], []
    n = len(path)
    for i, p in enumerate(path):
        a = path[max(i - 1, 0)]
        b = path[min(i + 1, n - 1)]
        dx, dy = b[0] - a[0], b[1] - a[1]
        L = math.hypot(dx, dy) or 1.0
        nx, ny = -dy / L, dx / L
        left.append((p[0] + nx * half, p[1] + ny * half))
        right.append((p[0] - nx * half, p[1] - ny * half))
    return left + right[::-1]


# ============================================================================ site skeleton
BOUNDARY = [tuple(p) for p in LAYOUT['boundary_ring']]
BOUNDARY_SF = LAYOUT['boundary_sf']
PARCELS = LAYOUT['parcels']
PINS = ['6123 033', '6123 015', '6123 014', '6123 162']
BEARINGS = LAYOUT['bearings']
METRICS = LAYOUT['metrics']

NE_LINE = sorted([p for p in BOUNDARY if p[1] > -100 and p[0] >= -0.05], key=lambda p: p[0])
SW_LINE = sorted([p for p in BOUNDARY if p[1] < -230], key=lambda p: p[0])
FRONT_LINE = sorted([p for p in BOUNDARY if p[0] <= 0.05 and p[1] >= -235], key=lambda p: -p[1])
REAR_LINE = sorted([p for p in BOUNDARY if p[0] > 1700], key=lambda p: p[1])
U_REAR = min(p[0] for p in REAR_LINE)


def NE(u):
    return interp_v(NE_LINE, u)


def SW(u):
    return interp_v(SW_LINE, u)


def front_u(v):
    return interp_v(sorted([(p[1], p[0]) for p in FRONT_LINE]), v)


def width(u):
    return NE(u) - SW(u)


def is_frontage_seg(a, b):
    return a[0] <= 0.05 and b[0] <= 0.05 and a[1] <= 0.05 and b[1] <= 0.05


# --- WGS84 <-> local (u, v): least-squares affine fit to the 90 3DEP samples in
#     data/topo-samples.json, each of which carries u, v, lon and lat. Residual is
#     reported by the self-check (it is under 0.01 ft), so lon/lat source geometry —
#     e.g. public building footprints — can be brought into the drawing without any
#     hand-transcribed local coordinates.
def _fit_affine():
    S = TOPO['samples']
    rows = [[s['u'], s['v'], 1.0] for s in S]

    def solve(ys):
        A = [[0.0] * 3 for _ in range(3)]
        B = [0.0] * 3
        for r, y in zip(rows, ys):
            for i in range(3):
                B[i] += r[i] * y
                for j in range(3):
                    A[i][j] += r[i] * r[j]
        M = [A[i] + [B[i]] for i in range(3)]
        for i in range(3):
            p = max(range(i, 3), key=lambda k: abs(M[k][i]))
            M[i], M[p] = M[p], M[i]
            for k in range(3):
                if k != i:
                    f = M[k][i] / M[i][i]
                    for j in range(i, 4):
                        M[k][j] -= f * M[i][j]
        return [M[i][3] / M[i][i] for i in range(3)]

    return solve([s['lon'] for s in S]), solve([s['lat'] for s in S])


_LON, _LAT = _fit_affine()
_DET = _LON[0] * _LAT[1] - _LON[1] * _LAT[0]


def uv_of(lon, lat):
    """WGS84 degrees -> site-local (u, v) feet."""
    dx, dy = lon - _LON[2], lat - _LAT[2]
    return ((_LAT[1] * dx - _LON[1] * dy) / _DET, (-_LAT[0] * dx + _LON[0] * dy) / _DET)


def lonlat_of(u, v):
    return (_LON[0] * u + _LON[1] * v + _LON[2], _LAT[0] * u + _LAT[1] * v + _LAT[2])


def affine_residual_ft():
    """Max |fit - source| over the 90 samples, in feet (1 deg latitude ~ 364,000 ft)."""
    worst = 0.0
    for s in TOPO['samples']:
        lo, la = lonlat_of(s['u'], s['v'])
        worst = max(worst, abs(lo - s['lon']) * 303000.0, abs(la - s['lat']) * 364000.0)
    return worst


# ============================================================================ adjoiner roster
# Gwinnett 2026 digest address for PIN R6123 024 is 225 King David Dr SW (docs/06 line 30).
# data/adjoining-parcels.json and data/site-context-local.json both carry "255" for it, which
# duplicates PIN R6123 021 — the defect the 2026-09-03 completeness audit records at item 8(d).
ADDRESS_FIX = {'6123 024': '225'}
STREET_OF = {'6123 017': 'Arcado Rd SW', '6123 036': 'Nantucket Dr', '6123 037': 'Nantucket Dr',
             '6123 038': 'Nantucket Dr', '6123 312': 'Fieldhouse Cir', '6123 313': 'Fieldhouse Cir'}
ROSTER = {a['PIN']: a for a in ADJOIN_ROSTER}


def street_of(pin):
    if pin in STREET_OF:
        return STREET_OF[pin]
    n = int(pin.split()[1])
    if 20 <= n <= 32:
        return 'King David Dr'
    if 300 <= n <= 313:
        return 'Village Green Ct'
    return ''


def address_of(pin):
    a = ADDRESS_FIX.get(pin) or (ROSTER.get(pin) or {}).get('ADDRESS') or ''
    return ('%s %s' % (a, street_of(pin))).strip()


def owner_of(pin):
    recs = OWNERS.get(pin) or []
    return (recs[0].get('OWNERNAME1') or 'owner VERIFY') if recs else 'owner VERIFY (Tax Assessor)'


# ============================================================================ existing improvements
# Building footprints and the 4541 drive are public aerial-imagery footprints published in
# OpenStreetMap (c) OpenStreetMap contributors, ODbL; the two building ways carry the
# Microsoft/Bing ML "BuildingFootprints" lineage. WGS84 vertices are quoted here exactly as
# the source publishes them and are converted to site-local feet by uv_of() above, so no
# local coordinate in this file is hand-drawn. Extents were checked against Esri World
# Imagery on 2026-09-03: both footprints sit on a visible roof, and the drive on a visible
# track. They are APPROXIMATE and must be located by survey.
#
# Areas below are computed from the polygons at run time and printed by the self-check;
# the tax-record areas they are compared with are 2,053 SF heated at 4541 (split-level,
# built 1972) and 4,267 SF heated at 4535 (built 1987, full finished basement) —
# docs/11-site-context-brief.md, Gwinnett 2026 digest.
EXISTING_STRUCTURES = [
    {'key': '4541-house', 'label': 'EXISTING HOUSE — 4541 ARCADO RD SW',
     'sub': ['PIN R6123 033 · built 1972 · brick split-level', '2,053 SF heated (2026 digest)'],
     'osm': 'OSM way 999395123', 'kind': 'building',
     'lonlat': [(-84.1201100, 33.8803310), (-84.1200280, 33.8803630), (-84.1200720, 33.8804410),
                (-84.1202550, 33.8803710), (-84.1201920, 33.8802580), (-84.1200900, 33.8802970)]},
    {'key': '4535-house', 'label': 'EXISTING HOUSE — 4535 ARCADO RD SW',
     'sub': ['PIN R6123 162 · built 1987 · full finished basement', '4,267 SF heated (2026 digest)'],
     'osm': 'OSM way 999395265', 'kind': 'building',
     'lonlat': [(-84.1214980, 33.8827990), (-84.1214640, 33.8827240), (-84.1213930, 33.8827460),
                (-84.1214900, 33.8829590), (-84.1217040, 33.8828930), (-84.1216580, 33.8827910),
                (-84.1216940, 33.8827800), (-84.1216780, 33.8827430)]},
]
EXISTING_DRIVE = {
    'key': '4541-drive', 'label': 'EXISTING DRIVE TO 4541 (approx. 12 ft wide)', 'osm': 'OSM way 913015145',
    'width_ft': 12.0,
    'lonlat': [(-84.1198650, 33.8796331), (-84.1199760, 33.8797799), (-84.1201118, 33.8799834),
               (-84.1202094, 33.8801502), (-84.1202262, 33.8802300), (-84.1202262, 33.8802592)],
}

# Mown-yard clearings digitised from public aerial imagery (Esri World Imagery, accessed
# 2026-09-03) at the two houses; everything else inside the boundary reads as woodland,
# which agrees with docs/11 ("the rear two-thirds is Piedmont hardwood") and FACTS section 2
# ("wooded rear"). Limits are APPROXIMATE and are the "areas of existing vegetation" element
# of Lilburn Zoning Ordinance 2023-603 section 1003-4.6 — no tree survey has been performed.
CLEARINGS = [
    {'key': 'yard-4541', 'polygon': rect(120.0, 272.0, -237.0, -128.0)},
    {'key': 'yard-4535', 'polygon': rect(1058.0, 1302.0, -196.0, -44.0)},
]


def existing_polys():
    """[(record, polygon in u/v feet, area_sf)] for the mapped buildings."""
    out = []
    for s in EXISTING_STRUCTURES:
        poly = [uv_of(*p) for p in s['lonlat']]
        out.append((s, poly, abs(poly_area(poly))))
    return out


def existing_drive_poly():
    path = [uv_of(*p) for p in EXISTING_DRIVE['lonlat']]
    return path, offset_band(path, EXISTING_DRIVE['width_ft'] / 2.0)


# ============================================================================ drawing primitives
class Labeler:
    """Greedy label-collision avoidance in sheet points; nudges along y (from siteplan.py)."""

    def __init__(self):
        self.boxes = []

    def hit(self, b):
        return any(not (b[2] < o[0] or b[0] > o[2] or b[3] < o[1] or b[1] > o[3]) for o in self.boxes)

    def place(self, x, y, w, h, anchor='middle'):
        for k in range(0, 9):
            for sgn in (1, -1) if k else (1,):
                yy = y + sgn * k * (h + 1.5)
                x0 = x - w / 2 if anchor == 'middle' else (x if anchor == 'start' else x - w)
                b = (x0, yy - h * 0.8, x0 + w, yy + h * 0.3)
                if not self.hit(b):
                    self.boxes.append(b)
                    return yy
        self.boxes.append((x - w / 2, y - h, x + w / 2, y))
        return y

    def reserve(self, x0, y0, x1, y1):
        self.boxes.append((x0, y0, x1, y1))


_CLIP = [0]


class Drawing:
    """SVG collector. Plan methods take (u, v) feet; the s* methods take sheet points."""

    def __init__(self, s, x0, y0, fs=1.0, win=WIN):
        self.s, self.x0, self.y0, self.fs, self.win = s, x0, y0, fs, win
        self.out, self.late = [], []
        self.lab = Labeler()

    # -- transforms
    def X(self, u):
        return self.x0 + (u - self.win[0]) * self.s

    def Y(self, v):
        return self.y0 + (self.win[3] - v) * self.s

    def P(self, p):
        return '%.2f,%.2f' % (self.X(p[0]), self.Y(p[1]))

    def box(self):
        u0, u1, v0, v1 = self.win
        return (self.X(u0), self.Y(v1), (u1 - u0) * self.s, (v1 - v0) * self.s)

    # -- raw
    def add(self, t):
        self.out.append(t)

    def later(self, fn):
        self.late.append(fn)

    # -- plan-coordinate primitives
    def poly(self, pts, **kw):
        self.add('<polygon points="%s" %s/>' % (' '.join(self.P(p) for p in pts), attrs(kw)))

    def pline(self, pts, **kw):
        self.add('<polyline points="%s" %s/>' % (' '.join(self.P(p) for p in pts), attrs(kw)))

    def line(self, a, b, **kw):
        self.add('<line x1="%.2f" y1="%.2f" x2="%.2f" y2="%.2f" %s/>'
                 % (self.X(a[0]), self.Y(a[1]), self.X(b[0]), self.Y(b[1]), attrs(kw)))

    def circle(self, c, r_pt, **kw):
        self.add('<circle cx="%.2f" cy="%.2f" r="%.2f" %s/>' % (self.X(c[0]), self.Y(c[1]), r_pt, attrs(kw)))

    def tw(self, text, size):
        return 0.56 * size * self.fs * len(str(text))

    def text(self, u, v, t, size=6, anchor='middle', rot=0, bold=False, fill='#111', halo=False,
             avoid=False, dy=0):
        size = size * self.fs
        x, y = self.X(u), self.Y(v) + dy
        if avoid and rot == 0:
            y = self.lab.place(x, y, self.tw(t, size / self.fs), size, anchor)
        tr = ' transform="rotate(%.2f %.2f %.2f)"' % (rot, x, y) if rot else ''
        st = 'font-size="%.2f" text-anchor="%s" fill="%s"%s' % (size, anchor, fill, ' font-weight="bold"' if bold else '')
        if halo:
            self.add('<text x="%.2f" y="%.2f" %s stroke="#fff" stroke-width="%.2f" stroke-linejoin="round"%s>%s</text>'
                     % (x, y, st, size * 0.45, tr, esc(t)))
        self.add('<text x="%.2f" y="%.2f" %s%s>%s</text>' % (x, y, st, tr, esc(t)))

    def textlines(self, u, v, lines, size=6, anchor='middle', gap=1.15, avoid=False, bold_first=False,
                  fill='#111', halo=False):
        h = size * self.fs * gap
        x, y = self.X(u), self.Y(v)
        if avoid:
            w = max(self.tw(l, size) for l in lines)
            y = self.lab.place(x, y, w, h * len(lines), anchor)
        for i, l in enumerate(lines):
            st = ('font-size="%.2f" text-anchor="%s" fill="%s"%s'
                  % (size * self.fs, anchor, fill, ' font-weight="bold"' if (bold_first and i == 0) else ''))
            if halo:
                self.add('<text x="%.2f" y="%.2f" %s stroke="#fff" stroke-width="%.2f" stroke-linejoin="round">%s</text>'
                         % (x, y + i * h, st, size * self.fs * 0.45, esc(l)))
            self.add('<text x="%.2f" y="%.2f" %s>%s</text>' % (x, y + i * h, st, esc(l)))

    def rot_of(self, a, b):
        dx, dy = self.X(b[0]) - self.X(a[0]), self.Y(b[1]) - self.Y(a[1])
        ang = math.degrees(math.atan2(dy, dx))
        if ang > 90:
            ang -= 180
        if ang < -90:
            ang += 180
        return ang

    # -- sheet-point primitives
    def srect(self, x, y, w, h, **kw):
        self.add('<rect x="%.2f" y="%.2f" width="%.2f" height="%.2f" %s/>' % (x, y, w, h, attrs(kw)))

    def sline(self, x0, y0, x1, y1, **kw):
        self.add('<line x1="%.2f" y1="%.2f" x2="%.2f" y2="%.2f" %s/>' % (x0, y0, x1, y1, attrs(kw)))

    def spoly(self, pts, **kw):
        self.add('<polygon points="%s" %s/>' % (' '.join('%.2f,%.2f' % p for p in pts), attrs(kw)))

    def scircle(self, x, y, r, **kw):
        self.add('<circle cx="%.2f" cy="%.2f" r="%.2f" %s/>' % (x, y, r, attrs(kw)))

    def stext(self, x, y, t, size=7, anchor='start', bold=False, fill='#111', rot=0, italic=False):
        tr = ' transform="rotate(%.2f %.2f %.2f)"' % (rot, x, y) if rot else ''
        self.add('<text x="%.2f" y="%.2f" font-size="%.2f" text-anchor="%s" fill="%s"%s%s%s>%s</text>'
                 % (x, y, size, anchor, fill, ' font-weight="bold"' if bold else '',
                    ' font-style="italic"' if italic else '', tr, esc(t)))

    def stextblock(self, x, y, text, size=6.5, chars=120, lead=8.2, fill='#111', bold=False, indent=0.0):
        for j, ln in enumerate(wrap(text, chars)):
            self.stext(x + (0 if j == 0 else indent), y, ln, size=size, fill=fill, bold=bold)
            y += lead
        return y

    # -- clip helper
    def clip_open(self, poly=None, fill='#fff'):
        _CLIP[0] += 1
        cid = 'clip%d' % _CLIP[0]
        x, y, w, h = self.box()
        shape = ('<polygon points="%s"/>' % ' '.join(self.P(p) for p in poly)) if poly else \
                ('<rect x="%.2f" y="%.2f" width="%.2f" height="%.2f"/>' % (x, y, w, h))
        self.add('<clipPath id="%s">%s</clipPath>' % (cid, shape))
        self.add('<g clip-path="url(#%s)" font-family=%s>' % (cid, '"' + FONT.replace("'", '') + '"'))
        if fill:
            self.add('<rect x="%.2f" y="%.2f" width="%.2f" height="%.2f" fill="%s"/>' % (x, y, w, h, fill))
        return cid

    def clip_close(self):
        self.add('</g>')

    def render(self):
        return '\n'.join(self.out)


def table(D, x, y, cols, rows, size=6.5, rowh=None, widths=None, title=None, head_fill='#e8e8e8'):
    """Simple ruled table in sheet points (from siteplan.py); returns the bottom y."""
    rowh = rowh or size * 1.45
    widths = widths or [140] * len(cols)
    W = sum(widths)
    if title:
        D.stext(x, y, title, size=size + 2.5, bold=True)
        y += size + 4
    y_top = y
    D.srect(x, y, W, rowh, fill=head_fill, stroke='#000', stroke_width=0.6)
    cx = x
    for c, w in zip(cols, widths):
        D.stext(cx + 3, y + rowh * 0.72, c, size=size, bold=True)
        cx += w
    y += rowh
    for r in rows:
        nl = max(len(wrap(str(c), max(int(w / (0.56 * size)), 4))) for c, w in zip(r, widths))
        h = rowh * nl
        D.srect(x, y, W, h, fill='none', stroke='#000', stroke_width=0.4)
        cx = x
        for c, w in zip(r, widths):
            for i, ln in enumerate(wrap(str(c), max(int(w / (0.56 * size)), 4))):
                D.stext(cx + 3, y + rowh * 0.72 + i * rowh, ln, size=size)
            cx += w
        y += h
    cx = x
    for w in widths[:-1]:
        cx += w
        D.sline(cx, y_top, cx, y, stroke='#000', stroke_width=0.4)
    return y


# ============================================================================ sheet frame
def sheet(title, sheet_no, subtitle, scale_note, status='DRAFT — NOT SEALED',
          status_lines=None, generator='tools/sitebase.py', north_at=None, scale_at=None,
          win=WIN, scale=SCALE60, x0=PLAN_X0, y0=PLAN_Y0):
    """Open an ARCH D 36 x 24 sheet and draw its frame, title block and disclaimer.

    Returns (Drawing, frame) where frame carries the sheet-point geometry a sheet body
    needs: plan window, the lower band, the title-block top and the inner margins.
    The north arrow and the graphic scale bar are queued with D.later() so that they are
    painted on top of every layer the caller adds afterwards.
    """
    M, IN_ = MARGIN, INNER
    D = Drawing(scale, x0, y0, fs=1.0, win=win)
    D.add('<svg xmlns="http://www.w3.org/2000/svg" width="36in" height="24in" viewBox="0 0 %d %d" font-family="%s">'
          % (SHEET_W, SHEET_H, FONT))
    D.add('<title>%s</title>' % esc('%s — %s — Sheet %s' % (PROJECT.title(), title, sheet_no)))
    D.add(DEFS)
    D.srect(0, 0, SHEET_W, SHEET_H, fill='#fff')
    D.srect(M, M, SHEET_W - 2 * M, SHEET_H - 2 * M, fill='none', stroke='#000', stroke_width=2)
    D.srect(M + IN_, M + IN_, SHEET_W - 2 * M - 2 * IN_, SHEET_H - 2 * M - 2 * IN_,
            fill='none', stroke='#000', stroke_width=0.6)

    # ---- title block (cell grid identical to Sheet C-1)
    tb_y, tb_h = TB_Y, TB_H - 6
    D.srect(M + IN_, tb_y, SHEET_W - 2 * M - 2 * IN_, tb_h, fill='#fff', stroke='#000', stroke_width=1.2)
    cells = [0, 820, 1330, 1780, 2180, SHEET_W - 2 * M - 2 * IN_]
    for cx in cells[1:-1]:
        D.sline(M + IN_ + cx, tb_y, M + IN_ + cx, tb_y + tb_h, stroke='#000', stroke_width=0.8)
    bx = M + 8
    D.stext(bx, tb_y + 30, PROJECT, size=22, bold=True)
    D.stext(bx, tb_y + 52, '%s — Rezoning R-1 → R-2 (City of Lilburn, Georgia)' % title, size=13, bold=True)
    D.stext(bx, tb_y + 70, '%s — %s' % (ADDRESSES, LEGAL), size=9)
    D.stext(bx, tb_y + 86, subtitle, size=9)
    bx = M + IN_ + cells[1] + 8
    D.stext(bx, tb_y + 18, 'APPLICANT / OWNER', size=8, fill='#555')
    D.stext(bx, tb_y + 34, APPLICANT, size=11, bold=True)
    D.stext(bx, tb_y + 48, '4541 Arcado Rd SW, Lilburn GA 30047-3968 (parcels 033, 015); Mendez / Roblero de Leon', size=7)
    D.stext(bx, tb_y + 58, '(parcels 014, 162) — co-applicants, owner signatures required', size=7)
    D.stext(bx, tb_y + 74, 'PREPARED FOR', size=8, fill='#555')
    D.stext(bx, tb_y + 88, 'Pre-application conference, City of Lilburn Planning & Zoning (340 Main St) —', size=8)
    D.stext(bx, tb_y + 98, 'rezoning application per Ord. 2023-603 §1003 (2026 Application Instructions)', size=8)
    bx = M + IN_ + cells[2] + 8
    D.stext(bx, tb_y + 18, 'STATUS', size=8, fill='#555')
    D.stext(bx, tb_y + 38, status, size=14, bold=True, fill='#c00')
    for k, ln in enumerate(status_lines or [
            'Existing conditions compiled from public records for pre-application',
            'review. Boundary from Gwinnett GIS — RLS boundary survey required and',
            'governs. Topography USGS 3DEP (approximate). To be superseded by a',
            'sealed RLS boundary and topographic survey and PE civil design.']):
        D.stext(bx, tb_y + 54 + k * 11, ln, size=8)
    D.stext(bx, tb_y + 100, 'Generator: %s' % generator, size=8)
    bx = M + IN_ + cells[3] + 8
    for k, (a, b) in enumerate([('DATE', DATE), ('SCALE', scale_note),
                                ('DATUM', 'SR 2240 GA West US-ft; NAVD88'),
                                ('DRAWN', 'owner-prepared (AI-assisted)'),
                                ('CHECKED', 'RLS / PE — pending')]):
        D.stext(bx, tb_y + 16 + k * 18, a, size=7.5, fill='#555')
        D.stext(bx + 55, tb_y + 16 + k * 18, b, size=8.5)
    bx = M + IN_ + cells[4] + 8
    D.stext(bx, tb_y + 18, 'SHEET', size=8, fill='#555')
    D.stext(bx + 150, tb_y + 72, sheet_no, size=54, bold=True, anchor='middle')
    D.stext(bx + 150, tb_y + 92, title, size=8, anchor='middle')

    # ---- disclaimer strip (house rule: every drawing carries it, with the marker)
    dy = TB_Y - 46
    D.srect(M + IN_, dy, SHEET_W - 2 * M - 2 * IN_, 40, fill='#fff8e1', stroke='#b00', stroke_width=0.8)
    D.stext(M + IN_ + 8, dy + 15, 'Disclaimer: ' + DISCLAIMER.split('Disclaimer: ')[-1], size=9,
            bold=True, fill='#7a0000')
    D.stext(M + IN_ + 8, dy + 30,
            'Label: DRAFT / NOT SEALED — every item that must be sealed by a Georgia RLS, PE, architect or '
            'landscape architect is shown as a concept only. Statements of conformity read "appears consistent with".',
            size=8, fill='#7a0000')
    D.add('<!-- %s -->' % MARKER)

    # ---- plan window outline + labels
    px, py, pw, ph = D.box()
    D.later(lambda: D.srect(px, py, pw, ph, fill='none', stroke='#000', stroke_width=1))
    D.stext(px, py - 8, '%s — %s  (site-local coordinates: +u along the strip to the NW, '
                        '+v across toward the NE line; see north arrow)'
            % (title.upper(), scale_note.split('(')[0].strip().upper()), size=11, bold=True)
    D.later(lambda: D.add('<text x="%.1f" y="%.1f" font-size="40" fill="#c00" fill-opacity="0.09" '
                          'font-weight="bold" text-anchor="middle" transform="rotate(-8 %.1f %.1f)">'
                          'DRAFT — NOT SEALED — EXISTING CONDITIONS OF RECORD, NOT A SURVEY</text>'
                          % (px + pw / 2, py + ph / 2, px + pw / 2, py + ph / 2)))
    na = north_at or (px + pw - 105, py + 78)
    sa = scale_at or (px + pw - 460, py + ph - 34)
    D.later(lambda: north_arrow(D, na[0], na[1]))
    D.later(lambda: scalebar(D, sa[0], sa[1], scale=scale))

    frame = {'W': SHEET_W, 'H': SHEET_H, 'M': M, 'inner_l': M + IN_ + 10, 'inner_r': SHEET_W - M - IN_ - 10,
             'plan': (px, py, pw, ph), 'band_y0': BAND_Y0, 'band_y1': BAND_Y1, 'tb_y': TB_Y,
             'sheet_no': sheet_no, 'title': title}
    return D, frame


def finish(D):
    """Close the SVG (running the queued late layers) and append the disclaimer marker."""
    for fn in D.late:
        fn()
    D.add('</svg>')
    return D.render() + '\n<!-- %s -->\n<!-- %s -->\n' % (DISCLAIMER, MARKER)


def save(D, basename, dpi=150):
    """Write drawings/<basename>.svg and .png. Returns both paths."""
    svg_path = os.path.join(DRAW, basename + '.svg')
    png_path = os.path.join(DRAW, basename + '.png')
    os.makedirs(DRAW, exist_ok=True)
    with open(svg_path, 'w') as fh:
        fh.write(finish(D))
    fp.render_png(svg_path, png_path, dpi=dpi)
    return svg_path, png_path


# ============================================================================ north arrow / scale bar
def north_arrow(c, x, y, r=30.0):
    """Grid-north arrow at sheet point (x, y). North is NORTH_DEG above the +u axis, and
    +v is up on the drawing, so on paper north points up and to the right."""
    a = math.radians(NORTH_DEG)
    dx, dy = math.cos(a), -math.sin(a)
    px, py = -dy, dx
    c.scircle(x, y, r, fill='#fff', stroke='#000', stroke_width=0.8)
    tip = (x + dx * r * 0.86, y + dy * r * 0.86)
    tail = (x - dx * r * 0.78, y - dy * r * 0.78)
    c.sline(tail[0], tail[1], tip[0], tip[1], stroke='#000', stroke_width=2.0)
    c.spoly([tip, (tip[0] - 17 * dx + 6.0 * px, tip[1] - 17 * dy + 6.0 * py),
             (tip[0] - 17 * dx - 6.0 * px, tip[1] - 17 * dy - 6.0 * py)], fill='#000')
    c.stext(tip[0] + 11 * dx, tip[1] + 11 * dy + 4, 'N', size=13, bold=True, anchor='middle')
    c.stext(x, y + r + 11, 'GRID NORTH (SR 2240 GA WEST)', size=6, anchor='middle')
    c.stext(x, y + r + 19, '= 28°43\' ABOVE THE +u AXIS', size=6, anchor='middle')


def scalebar(c, x, y, scale=SCALE60, step_ft=60, steps=4):
    """Graphic scale bar at sheet point (x, y) = left end of the bar."""
    h = 7.0
    for k in range(steps):
        c.srect(x + step_ft * scale * k, y, step_ft * scale, h,
                fill='#000' if k % 2 == 0 else '#fff', stroke='#000', stroke_width=0.6)
        c.stext(x + step_ft * scale * k, y - 4, str(step_ft * k), size=6.5, anchor='middle')
    c.stext(x + step_ft * scale * steps, y - 4, '%d ft' % (step_ft * steps), size=6.5, anchor='middle')
    c.stext(x + step_ft * scale * steps / 2.0, y + h + 11,
            'GRAPHIC SCALE  1" = %d\'' % round(72.0 / scale), size=8, bold=True, anchor='middle')


# ============================================================================ enlargements
ENLARGEMENTS = []          # filled by a sheet before it calls match_lines()


def enlargement(u0, u1, v0, v1, x, y, scale=SCALE30, tag='A'):
    """A second Drawing that crops the u-range [u0, u1] (and v-range) at 1" = 30' by default.
    Draw the same layer functions into it, then place() it on the sheet."""
    D2 = Drawing(scale, x, y, fs=1.0, win=(u0, u1, v0, v1))
    D2.tag = tag
    return D2


def place(D, sub, title=None, note=None):
    """Paste an enlargement onto the sheet with its border and caption."""
    x, y, w, h = sub.box()
    if title:
        D.stext(x, y - 16, title, size=9, bold=True)
    if note:
        D.stext(x, y - 6, note, size=6.5, fill='#444')
    D.add(sub.render())
    for fn in sub.late:
        fn()
        D.add(sub.out.pop())
    D.srect(x, y, w, h, fill='none', stroke='#000', stroke_width=1)
    D.srect(x + 3, y + 3, 86, 14, fill='#fff', stroke=C['match'], stroke_width=0.8)
    D.stext(x + 7, y + 13.5, 'ENLARGEMENT %s' % getattr(sub, 'tag', ''), size=8.5, bold=True, fill=C['match'])
    return y + h


def match_lines(c, regions=None):
    """Draw the match-line box(es) for the enlargements on the full-length layout."""
    for (u0, u1, v0, v1, tag) in (regions if regions is not None else ENLARGEMENTS):
        c.poly(rect(u0, u1, v0, v1), fill='none', stroke=C['match'], stroke_width=1.1,
               stroke_dasharray='16 5 3 5')
        c.text((u0 + u1) / 2.0, v1 + 6, 'MATCH LINE — SEE ENLARGEMENT %s (1" = 30\')' % tag,
               size=7, bold=True, fill=C['match'], halo=True)


# ============================================================================ layers — existing
def adjoiners(c, labels=True, zoning=True):
    """Adjoining tax parcels with PIN, owner and zoning; plus the nearby Lilburn R-2 polygon."""
    c.add('<g id="adjoining">')
    for a in CTX['adjoining_parcels']:
        ring = [tuple(p) for p in a['ring_local']]
        if a['PIN'] == 'R/W':
            continue
        c.poly(ring, fill=C['adj_fill'], stroke=C['adj_line'], stroke_width=0.5)
    c.add('</g>')
    if zoning:
        for z in CTX['zoning']:
            if z['type'] == 'R2':
                c.poly([tuple(p) for p in z['ring_local']], fill='url(#r2hatch)', stroke='#c8791a',
                       stroke_width=0.8, stroke_dasharray='6 3')
    if not labels:
        return
    for a in CTX['adjoining_parcels']:
        if a['PIN'] == 'R/W':
            continue
        ring = [tuple(p) for p in a['ring_local']]
        ctr = poly_centroid(ring)
        if a['PIN'] == '6123 017':
            ctr = (165, 62)
        if a['PIN'] in ('6123 036', '6123 037', '6123 038'):
            ctr = (ctr[0] - 15, ctr[1])
        lines = (['PIN R%s' % a['PIN'], address_of(a['PIN'])] + wrap(owner_of(a['PIN']), 22)
                 + ['Zoned R-1 (City of Lilburn)'])
        c.textlines(ctr[0], ctr[1] + 12, lines, size=6, gap=1.18, avoid=True, fill=C['adj_text'])
    if zoning:
        c.text(60, 212, 'R-2 (Lilburn) — existing', size=7.5, bold=True, fill='#8a4b00', halo=True)
        c.text(60, 202, '"Arcado Road Townhomes" site — nearest R-2 precedent (≈106 ft NE of the front corner)',
               size=6, fill='#8a4b00', halo=True)


def arcado_row(c, labels=True):
    """The Arcado Rd right-of-way lines (Gwinnett GIS R/W parcel) and the centreline."""
    rw = [a for a in CTX['adjoining_parcels'] if a['PIN'] == 'R/W']
    c.add('<g id="row">')
    for a in rw:
        run, cur = [], []
        for p in a['ring_local']:
            if c.win[0] - 60 < p[0] < c.win[1] + 60 and c.win[2] - 60 < p[1] < c.win[3] + 60:
                cur.append(tuple(p))
            else:
                if len(cur) > 1:
                    run.append(cur)
                cur = []
        if len(cur) > 1:
            run.append(cur)
        for path in run:
            c.pline(path, fill='none', stroke=C['rw'], stroke_width=0.9)
    for st in CTX['streets']:
        if st['name'] == 'ARCADO RD' and st['min_dist_ft'] < 70:
            for path in st['paths_local']:
                c.pline([tuple(p) for p in path], fill='none', stroke='#333', stroke_width=0.6,
                        stroke_dasharray='14 3 3 3')
        elif st['name'] == 'ARCADIA PL' and st['min_dist_ft'] < 100:
            for path in st['paths_local']:
                c.pline([tuple(p) for p in path], fill='none', stroke='#333', stroke_width=0.6,
                        stroke_dasharray='14 3 3 3')
        elif st['min_dist_ft'] < 260:
            for path in st['paths_local']:
                c.pline([tuple(p) for p in path], fill='none', stroke=C['rw'], stroke_width=0.5,
                        stroke_dasharray='14 3 3 3')
    c.add('</g>')
    if labels:
        c.text(-112, -40, 'ARCADO ROAD (Gwinnett County minor collector, 35 mph, 14,800 AADT, GDOT stn 135-6689) '
                          '— R/W WIDTH VARIES', size=8, rot=-81, bold=True)
        c.text(-58, -330, 'C/L ARCADO RD', size=6, rot=-81, halo=True)
        c.text(-95, -395, 'OPPOSITE R/W LINE (Gwinnett GIS)', size=6, rot=-81, halo=True)


def row_width_ft(vs=(-40.0, -120.0, -200.0, -235.0)):
    """Perpendicular R/W width at the given v stations, measured between the two GIS R/W
    lines. Returns [(v, width_ft)] — the input for the 'R/W WIDTH VARIES' note."""
    ring = [tuple(p) for p in [a for a in CTX['adjoining_parcels'] if a['PIN'] == 'R/W'][0]['ring_local']]
    run = [p for p in ring if -220 < p[0] < 420 and -520 < p[1] < 320]
    near = [p for p in run if p[0] > -70]
    far = [p for p in run if p[0] <= -70]
    out = []
    for v in vs:
        q = min(near, key=lambda p: abs(p[1] - v))
        d = min(_seg_pt(q, far[i], far[i + 1]) for i in range(len(far) - 1))
        out.append((v, d))
    return out


def _seg_pt(p, a, b):
    ax, ay = a
    bx, by = b
    dx, dy = bx - ax, by - ay
    L2 = dx * dx + dy * dy
    if L2 == 0:
        return dist(p, a)
    t = max(0.0, min(1.0, ((p[0] - ax) * dx + (p[1] - ay) * dy) / L2))
    return dist(p, (ax + t * dx, ay + t * dy))


def boundary(c, bearings=True, short_ft=60.0, label=True):
    """The assemblage boundary with per-course bearings and distances.
    Courses shorter than short_ft get a tag (L1, L2, ...) for the line table; the tags are
    returned so the sheet can print the table."""
    c.add('<g id="boundary">')
    c.poly(BOUNDARY, fill='none', stroke=C['bnd'], stroke_width=1.8)
    c.add('</g>')
    tags = []
    if not bearings:
        return tags
    n = 0
    for b in BEARINGS:
        a, d = tuple(b['from']), tuple(b['to'])
        m = ((a[0] + d[0]) / 2.0, (a[1] + d[1]) / 2.0)
        if b['distance_ft'] < short_ft:
            n += 1
            tag = 'L%d' % n
            tags.append((tag, b))
            if c.s >= SCALE30:
                dx, dy = d[0] - a[0], d[1] - a[1]
                L = math.hypot(dx, dy) or 1.0
                nx, ny = -dy / L, dx / L
                c.text(m[0] - nx * 7.0, m[1] - ny * 7.0, tag, size=6, bold=True, fill='#000', halo=True)
            elif not b['frontage']:
                c.text(m[0] + (10 if a[0] > 1700 else 0), m[1] + (0 if a[0] > 1700 else -12), tag,
                       size=6, fill='#000', avoid=True)
            continue
        dx, dy = d[0] - a[0], d[1] - a[1]
        L = math.hypot(dx, dy)
        nx, ny = -dy / L, dx / L
        c.text(m[0] - nx * 9.0, m[1] - ny * 9.0, "%s   %.2f'" % (b['bearing'], b['distance_ft']),
               size=6, rot=c.rot_of(a, d), fill='#000', dy=2)
    if label:
        c.text(front_u(-150) - 26, -150, 'ARCADO RD FRONTAGE COURSES %s (SEE LINE TABLE)'
               % tag_ranges(tags), size=6, rot=-81, fill='#000')
        c.text(1000, 165, 'ASSEMBLAGE: 9.44 AC (DEEDED) / %.2f AC (GIS CALC.) — LAND LOT 123, 6th DISTRICT — '
                          'BOUNDARY AND BEARINGS FROM THE GWINNETT GIS PARCEL FABRIC: DRAFT, RLS SURVEY REQUIRED '
                          'AND GOVERNS' % (BOUNDARY_SF / 43560.0), size=7, bold=True, halo=True)
    return tags


def tag_ranges(tags, frontage=True):
    """'L1–L7 AND L19–L25' — the line-table tags of the courses on (or off) the Arcado Rd frontage."""
    nums = [int(t[1:]) for t, b in tags if bool(b['frontage']) == bool(frontage)]
    runs, start, prev = [], None, None
    for n in nums + [None]:
        if start is None:
            start = prev = n
            continue
        if n == prev + 1:
            prev = n
            continue
        runs.append((start, prev))
        start = prev = n
    return ' AND '.join('L%d' % a if a == b else 'L%d–L%d' % (a, b) for a, b in runs)


def parcel_lines(c, labels=True, at=None):
    """The four interior parcel lines (to be combined) with PIN and deeded acreage."""
    c.add('<g id="parcels">')
    for pin in PINS:
        c.poly([tuple(p) for p in PARCELS[pin]['ring']], fill='none', stroke=C['parcel'],
               stroke_width=0.6, stroke_dasharray='10 4 2 4')
    c.add('</g>')
    if not labels:
        return
    at = at or {'6123 033': (150, -226), '6123 015': (480, -226), '6123 014': (1000, -12), '6123 162': (1470, -12)}
    for pin in PINS:
        p = PARCELS[pin]
        c.text(at[pin][0], at[pin][1], 'PIN R%s  (%s)  %.2f AC DEEDED / %.3f AC GIS'
               % (pin, p['address'].upper(), p['deeded_ac'], p['gis_ac']),
               size=6.5, bold=True, fill='#444', halo=True, avoid=True)


def contours(c, existing=True, proposed=None, labels=True):
    """Existing 2-ft contours (USGS 3DEP, NAVD88, approximate). `proposed` may be a
    {level: [polyline, ...]} dict supplied by a grading sheet; it draws heavier and solid."""
    if existing:
        c.add('<g id="contours">')
        for lev, lines in sorted(LAYOUT['contours_2ft'].items(), key=lambda kv: int(kv[0])):
            idx = int(lev) % 10 == 0
            for ln in lines:
                c.pline([tuple(p) for p in ln], fill='none', stroke=(C['contour_txt'] if idx else C['contour']),
                        stroke_width=(0.9 if idx else 0.45), stroke_dasharray='7 3' if idx else '3 2')
        if labels:
            for lev, lines in sorted(LAYOUT['contours_2ft'].items(), key=lambda kv: int(kv[0])):
                if int(lev) % 10:
                    continue
                for ln in lines:
                    for k in range(len(ln) - 1):
                        for ref in (lambda u: (SW(u) + NE(u)) / 2.0, lambda u: SW(u) + 9.0, lambda u: NE(u) - 9.0):
                            d0 = ln[k][1] - ref(ln[k][0])
                            d1 = ln[k + 1][1] - ref(ln[k + 1][0])
                            if (d0 > 0) != (d1 > 0):
                                t = d0 / (d0 - d1)
                                uc = ln[k][0] + t * (ln[k + 1][0] - ln[k][0])
                                c.text(uc, ref(uc) - 2.5, str(lev), size=6, fill=C['contour_txt'],
                                       halo=True, avoid=True)
        c.add('</g>')
    if proposed:
        c.add('<g id="contours-proposed">')
        for lev, lines in sorted(proposed.items(), key=lambda kv: int(kv[0])):
            for ln in lines:
                c.pline([tuple(p) for p in ln], fill='none', stroke='#6d4c2f',
                        stroke_width=(0.9 if int(lev) % 10 == 0 else 0.5))
        c.add('</g>')


def spot_elevations(c, picks=None, size=5.5):
    """A few labelled 3DEP spot elevations (the ridge, the swale, the rear low pocket)."""
    S = TOPO['samples']
    hi = max(S, key=lambda s: s['z_ft'])
    lo = min(S, key=lambda s: s['z_ft'])
    for s in (picks or [hi, lo]):
        c.circle((s['u'], s['v']), 1.6, fill='none', stroke=C['contour_txt'], stroke_width=0.6)
        c.line((s['u'] - 3, s['v']), (s['u'] + 3, s['v']), stroke=C['contour_txt'], stroke_width=0.5)
        c.line((s['u'], s['v'] - 3), (s['u'], s['v'] + 3), stroke=C['contour_txt'], stroke_width=0.5)
        c.text(s['u'] + 6, s['v'] - 4, '%.1f' % s['z_ft'], size=size, anchor='start',
               fill=C['contour_txt'], halo=True)
    return hi, lo


def streams_and_buffers(c, labels=True):
    """The unnamed stream (state waters) and its 25 / 50 / 75-ft buffer lines."""
    c.add('<g id="streams">')
    style = {'25': (C['buf_line'], '3 2', 0.5), '50': (C['buf_line'], '6 2', 0.8),
             '75': (C['buf_line'], '8 2 2 2', 0.8)}
    for s in LAYOUT['stream_setbacks']:
        for lv, lines in sorted(s['offsets'].items(), key=lambda kv: int(kv[0])):
            col, dash, w = style[lv]
            for ln in lines:
                c.pline([tuple(p) for p in ln], fill='none', stroke=col, stroke_width=w, stroke_dasharray=dash)
        c.pline([tuple(p) for p in s['stream']], fill='none', stroke=C['stream'], stroke_width=1.6)
    c.add('</g>')
    if not labels:
        return
    c.text(1455, -380, 'UNNAMED STREAM (state waters, order-0 headwater of Jackson Creek, GAR030701030315) — '
                       'TOP OF BANK APPROXIMATE, FIELD DELINEATION REQUIRED',
           size=6, fill=C['stream'], halo=True, anchor='end')
    so = LAYOUT['stream_setbacks'][0]['offsets']
    for lv, vv, txt in (('75', -262, "75' IMPERVIOUS SETBACK"), ('50', -276, "50' UNDISTURBED STREAM BUFFER (LILBURN)"),
                        ('25', -290, "25' STATE (GA EPD) BUFFER")):
        pts = [tuple(p) for ln in so[lv] for p in ln if p[0] < 1330]
        if not pts:
            continue
        p = min(pts, key=lambda q: abs(q[1] - vv))
        c.text(p[0] - 4, p[1], txt, size=6, fill=C['stream'], halo=True, anchor='end')
    c.text(1000, -258, "50'/75' BUFFERS OF THE OFF-SITE BRANCH (they clip the SW edge of the site ≤ 12 ft / ≤ 36 ft)",
           size=6, fill=C['stream'], halo=True, avoid=True)


def sewer_existing(c, labels=True, easement=True):
    """The existing 8-in gravity sewer, the 20-ft sanitary sewer easement and the manholes
    with their Gwinnett GIS invert elevations (GIS attributes — unsurveyed)."""
    runs = [s for s in CTX['sewer'] if s['min_dist_ft'] < 200]
    c.add('<g id="sewer">')
    if easement:
        for s in runs:
            if 'ARCADO' not in s['project']:
                continue
            for path in s['paths_local']:
                pts = [tuple(p) for p in path]
                mid = ((pts[0][0] + pts[-1][0]) / 2.0, (pts[0][1] + pts[-1][1]) / 2.0)
                if not point_in_poly(mid, BOUNDARY):
                    continue                       # only the reach that is on the property
                c.poly(offset_band(pts, 10.0), fill='url(#ssehatch)',
                       stroke=C['sewer'], stroke_width=0.4, stroke_dasharray='5 3')
    for s in runs:
        for path in s['paths_local']:
            c.pline([tuple(p) for p in path], fill='none', stroke=C['sewer'], stroke_width=0.9)
            for p in (path[0], path[-1]):
                c.circle(tuple(p), 2.2, fill='#fff', stroke=C['sewer'], stroke_width=0.7)
    c.add('</g>')
    if not labels:
        return
    c.text(-30, -62, 'EX. MH  INV 943.79 / 940.47', size=6, fill=C['sewer_txt'], halo=True, rot=-81)
    c.line((285.0, -222.0), (396.0, -206.0), stroke=C['sewer_txt'], stroke_width=0.5)
    c.text(400, -204.0, 'EX. MH  INV 927.13  (GIS ATTRIBUTE — UNSURVEYED)  —  Phase 1 point of connection',
           size=6, fill=C['sewer_txt'], halo=True, anchor='start')
    c.textlines(120, -269, ["EX. 8-in SANITARY SEWER IN A 20-ft SANITARY SEWER EASEMENT (\"EX. 20' SSE\") — Gwinnett DWR,",
                            "Arcado Road Townhomes outfall; the 20-ft width is from the 2025 hydrology sheet and is NOT a "
                            "surveyed plat dimension — VERIFY"],
                size=6, gap=1.25, fill=C['sewer_txt'], halo=True, anchor='start')
    c.text(1100, -420, 'EX. 8-in SANITARY SEWER — LEGENDS AT PARKVIEW (Gwinnett DWR)', size=6,
           fill=C['sewer_txt'], halo=True)
    c.text(1339, -418, 'EX. MH  INV 919.58  (GIS ATTRIBUTE — UNSURVEYED)', size=6, fill=C['sewer_txt'],
           halo=True, anchor='end')


def water_existing(c, labels=True):
    """Water mains in Arcado Rd and the hydrants (Gwinnett DWR GIS)."""
    c.add('<g id="water">')
    for w in CTX['water_mains_near']:
        for path in w['paths_local']:
            c.pline([tuple(p) for p in path], fill='none', stroke=C['water'], stroke_width=0.9,
                    stroke_dasharray='9 3 2 3')
    for h in CTX['hydrants']:
        p = tuple(h['local'])
        c.circle(p, 2.6, fill=C['hydrant'], stroke='#fff', stroke_width=0.5)
    c.add('</g>')
    if not labels:
        return
    near = min(CTX['hydrants'], key=lambda h: h['dist_ft'])
    c.text(near['local'][0] + 6, near['local'][1] - 2,
           'EX. FIRE HYDRANT at local (u %.0f, v %+.1f) — %.1f ft from the front corner'
           % (near['local'][0], near['local'][1], near['dist_ft']),
           size=6, fill=C['hydrant'], halo=True, anchor='start')
    c.text(-88, -150, 'EX. WATER MAINS IN ARCADO RD (DIP / ACP, Gwinnett DWR — sizes not published in the '
                      'public layer; VERIFY)', size=6, rot=-81, fill=C['water'], halo=True)


def wooded_area(c, labels=True):
    """Existing wooded area (section 1003-4.6 'areas of existing vegetation') — the site less
    the two mown yards, with the tree line shown at the yard limits."""
    c.add('<g id="woods">')
    c.clip_open(BOUNDARY, fill=None)
    c.poly(BOUNDARY, fill='url(#woods)', stroke='none')
    for g in CLEARINGS:
        c.poly(g['polygon'], fill='#fbf7ef', stroke='none')
    c.clip_close()
    for g in CLEARINGS:
        c.poly(g['polygon'], fill='none', stroke=C['wood_line'], stroke_width=0.9, stroke_dasharray='7 3 2 3')
    c.add('</g>')
    if not labels:
        return
    c.text(560, -60, 'EXISTING WOODED AREA — LIMITS APPROXIMATE, TO BE FIELD-VERIFIED', size=8,
           bold=True, fill=C['wood_txt'], halo=True)
    c.text(560, -72, 'Piedmont hardwood over eroded Appling / Madison / Pacolet clays; no tree survey performed',
           size=6, fill=C['wood_txt'], halo=True)
    for g, at, txt in ((CLEARINGS[0], (276.0, -150.0), 'TREE LINE (APPROX.) — MOWN YARD AT 4541'),
                       (CLEARINGS[1], (1062.0, -33.0), 'TREE LINE (APPROX.) — MOWN YARD AT 4535')):
        c.text(at[0], at[1], txt, size=6, fill=C['wood_line'], halo=True, anchor='start')


def existing_structures(c, labels=True):
    """The two existing houses and the mapped drive, drawn in place, dashed, to be removed."""
    c.add('<g id="existing">')
    path, band = existing_drive_poly()
    c.poly(band, fill='#efe6dc', stroke=C['exist'], stroke_width=0.6, stroke_dasharray='6 3')
    for s, poly, area in existing_polys():
        c.poly(poly, fill='url(#exhatch)', stroke=C['exist'], stroke_width=1.2, stroke_dasharray='7 3')
    c.add('</g>')
    if not labels:
        return
    at = {'4541-house': (203.0, -80.0, 'middle'), '4535-house': (1252.0, -52.0, 'start')}
    for s, poly, area in existing_polys():
        u, v, anc = at[s['key']]
        c.textlines(u, v, [s['label'], '%s ± SF FOOTPRINT (APPROXIMATE)' % format(round(area, -1), ',.0f')]
                    + s['sub'] + ['TO BE REMOVED'],
                    size=6, gap=1.22, bold_first=True, fill=C['exist'], halo=True, anchor=anc)
    c.text(60, -212, 'EXISTING DRIVE TO 4541 — TO BE REMOVED', size=6, fill=C['exist'],
           halo=True, anchor='start')
    c.line((150.0, -213.0), (150.0, -226.0), stroke=C['exist'], stroke_width=0.5)
    c.text(1058, -212, 'NO DRIVE TO 4535 IS RESOLVED IN THE FOOTPRINT SOURCE — TO BE LOCATED BY SURVEY',
           size=6, fill=C['exist'], halo=True, anchor='start')
    c.text(300, -176, 'APPROXIMATE — FROM AERIAL IMAGERY / TAX RECORDS, TO BE LOCATED BY SURVEY', size=7,
           bold=True, fill=C['exist'], halo=True, anchor='start')
    c.text(300, -187, 'Accessory structures are reported near the frontage (FACTS §2; docs/02 §2) but none is '
                      'resolved in the footprint source — inventory by survey before demolition permits.',
           size=6, fill=C['exist'], halo=True, anchor='start')


# ============================================================================ layers — proposed
def lots(c, labels=True):
    """The 43 proposed lots with their buffer easement and setback envelope."""
    c.add('<g id="lots">')
    for L in LAYOUT['lots']:
        c.poly([tuple(p) for p in L['polygon']], fill='#fff', stroke='#222', stroke_width=0.6)
        c.poly([tuple(p) for p in L['buffer_easement']], fill='url(#bufhatch)', stroke='none')
        c.poly([tuple(p) for p in L['setback_envelope']], fill='none', stroke='#999', stroke_width=0.3,
               stroke_dasharray='2 1.5')
        c.poly([tuple(p) for p in L['driveway_rect']], fill='#e2e2e2', stroke='#777', stroke_width=0.35)
        c.poly([tuple(p) for p in L['house_rect']], fill=C['house'], stroke='#222', stroke_width=0.6)
        c.poly([tuple(p) for p in L['garage_rect']], fill='#efd2ad', stroke='#222', stroke_width=0.45)
        for k in ('porch_rect', 'rear_rect'):
            c.poly([tuple(p) for p in L[k]], fill='#fdf3e4', stroke='#222', stroke_width=0.4)
    c.add('</g>')
    if not labels:
        return
    for L in LAYOUT['lots']:
        ctr = poly_centroid([tuple(p) for p in L['house_rect']])
        c.textlines(ctr[0], ctr[1] + 10.5, ['LOT %d' % L['id'], 'PLAN %s' % L['plan'],
                                            '%s SF' % format(L['area_sf'], ',.0f'),
                                            "%.0f' × %.0f'" % (L['width_ft'], L['depth_ft'])],
                    size=6, gap=1.2, bold_first=True)


def lane(c, labels=True):
    """The private lane tract, pavement, sidewalks, hammerheads and the entry drive."""
    ln = LAYOUT['lane']
    c.add('<g id="lane">')
    for key in ('tract_polygon',):
        c.poly([tuple(p) for p in ln[key]], fill=C['tract'], stroke='#666', stroke_width=0.5,
               stroke_dasharray='4 2')
    c.poly([tuple(p) for p in ln['entry_drive']['tract_polygon']], fill=C['tract'], stroke='#666',
           stroke_width=0.5, stroke_dasharray='4 2')
    c.poly([tuple(p) for p in ln['entry_drive']['pavement_polygon']], fill=C['pave'], stroke='#333',
           stroke_width=0.7)
    c.poly([tuple(p) for p in ln['pavement_polygon']], fill=C['pave'], stroke='#333', stroke_width=0.7)
    for h in LAYOUT['hammerheads']:
        for leg in h['legs']:
            c.poly([tuple(p) for p in leg], fill=C['pave'], stroke='#333', stroke_width=0.7)
    for s in ln['sidewalks']:
        c.poly([tuple(p) for p in s['polygon']], fill='#f7f7f7', stroke='#777', stroke_width=0.35)
    c.pline([tuple(p) for p in ln['centerline']], fill='none', stroke='#444', stroke_width=0.4,
            stroke_dasharray='12 3 2 3')
    c.add('</g>')
    if labels:
        cl = [tuple(p) for p in ln['centerline']]
        mid = cl[len(cl) // 2]
        c.text(mid[0], mid[1] + 5, "PRIVATE LANE — HOA TRACT %.0f'–%.0f' — 22' PVMT + 2' STRIP + 5' WALK"
               % (ln['tract_width_ft'][0], ln['tract_width_ft'][1]), size=6, bold=True)


def amenity(c, labels=True):
    """The front amenity block: clubhouse, village green, pickleball, parking, kiosk, sign."""
    A = LAYOUT['amenity']
    c.add('<g id="amenity">')
    for p in A['tract_polygons']:
        c.poly([tuple(q) for q in p], fill='#eef4e6', stroke=C['green_line'], stroke_width=0.4)
    c.poly([tuple(p) for p in A['village_green']], fill='#cfe8bd', stroke=C['green_line'], stroke_width=0.4)
    c.poly([tuple(p) for p in A['clubhouse']], fill='#f2c58a', stroke='#222', stroke_width=0.8)
    for pad, court in zip(A['pickleball'], A['courts']):
        c.poly([tuple(p) for p in pad], fill='#e9e2d0', stroke='#222', stroke_width=0.6)
        c.poly([tuple(p) for p in court], fill='#bcd7c2', stroke='#222', stroke_width=0.4)
    for k in ('parking_bay', 'kiosk_bay'):
        c.poly([tuple(p) for p in A[k]], fill=C['pave'], stroke='#333', stroke_width=0.5)
    for st in A['stalls'] + A['kiosk_stalls']:
        c.poly([tuple(p) for p in st], fill='none', stroke='#555', stroke_width=0.3)
    c.poly([tuple(p) for p in A['mail_kiosk']], fill='#f2c58a', stroke='#222', stroke_width=0.6)
    c.poly([tuple(p) for p in A['entry_sign']], fill='#333', stroke='none')
    c.add('</g>')
    if labels:
        ctr = poly_centroid([tuple(p) for p in A['clubhouse']])
        c.textlines(ctr[0], ctr[1] + 6, ['CLUBHOUSE', "%s SF  (40' × 60')" % format(A['clubhouse_sf'], ',')],
                    size=6, gap=1.2, bold_first=True)


def ponds(c, labels=True):
    """The two dry detention / water-quality ponds and their tracts."""
    c.add('<g id="ponds">')
    for p in LAYOUT['ponds']:
        c.poly([tuple(q) for q in p['tract_polygon']], fill='#e4efdc', stroke=C['green_line'], stroke_width=0.4)
        c.poly([tuple(q) for q in p['polygon']], fill=C['pond'], stroke=C['buf_line'], stroke_width=0.8,
               stroke_dasharray='5 2')
    c.add('</g>')
    if labels:
        for i, p in enumerate(LAYOUT['ponds'], 1):
            ctr = poly_centroid([tuple(q) for q in p['polygon']])
            c.textlines(ctr[0], ctr[1] + (30 if i == 2 else 8),
                        ['POND %d — DRY DETENTION / WQ' % i,
                         '%s ft TOB, 4 ft deep, 3:1' % p['top_of_bank_ft'],
                         '≈%s cf (assumption)' % format(p['est_storage_cf'], ',')],
                        size=6, gap=1.2, bold_first=True, fill='#0d47a1')


def open_space(c, labels=True):
    """Common open-space tracts: pocket greens, terminus green and the creek woods."""
    c.add('<g id="openspace">')
    for g in LAYOUT['greens']:
        for p in g['polygons']:
            c.poly([tuple(q) for q in p], fill=C['green'], stroke=C['green_line'], stroke_width=0.4)
    c.add('</g>')
    if labels:
        for g in LAYOUT['greens'][:2]:
            ctr = poly_centroid([tuple(q) for q in g['polygons'][0]])
            c.text(ctr[0], ctr[1] - 20, 'POCKET GREEN', size=6, bold=True, fill='#2e5e1e')


# ============================================================================ self-check
def _selfcheck():
    print('sitebase.py self-check —', DATE)
    print('  data      : layout.json (%d lots, %d bearings), site-context-local.json (%d adjoiners), '
          'topo-samples.json (%d samples)'
          % (len(LAYOUT['lots']), len(BEARINGS), len(CTX['adjoining_parcels']), len(TOPO['samples'])))
    print('  boundary  : %d courses, %.1f SF = %.3f ac GIS; u %.1f..%.1f, v %.1f..%.1f'
          % (len(BOUNDARY), BOUNDARY_SF, BOUNDARY_SF / 43560.0,
             min(p[0] for p in BOUNDARY), max(p[0] for p in BOUNDARY),
             min(p[1] for p in BOUNDARY), max(p[1] for p in BOUNDARY)))
    print('  width     : %.1f ft at u=0, %.1f ft at u=%.0f (FACTS §1: ~236 -> ~246)'
          % (width(0), width(U_REAR - 1), U_REAR - 1))
    print('  affine    : lon/lat <-> u,v residual %.4f ft over %d samples'
          % (affine_residual_ft(), len(TOPO['samples'])))
    for s, poly, area in existing_polys():
        ctr = poly_centroid(poly)
        inside = point_in_poly(ctr, BOUNDARY)
        print('  structure : %-28s %6.0f SF footprint at (u %.0f, v %.0f) inside=%s [%s]'
              % (s['key'], area, ctr[0], ctr[1], inside, s['osm']))
    print('  R/W width : ' + ', '.join('v %+.0f -> %.1f ft' % (v, w) for v, w in row_width_ft()))
    hi = max(TOPO['samples'], key=lambda s: s['z_ft'])
    lo = min(TOPO['samples'], key=lambda s: s['z_ft'])
    print('  topo      : high %.1f at (u %.0f, v %.0f); low %.1f at (u %.0f, v %.0f)'
          % (hi['z_ft'], hi['u'], hi['v'], lo['z_ft'], lo['u'], lo['v']))
    D, F = sheet('SELF CHECK', 'X-0', 'self-check only — nothing is written', 'Scale 1" = 60\' (ARCH D 36 × 24 in)')
    n0 = len(D.out)
    for fn in (adjoiners, arcado_row, wooded_area, contours, streams_and_buffers, sewer_existing,
               water_existing, boundary, parcel_lines, existing_structures, lots, lane, amenity,
               ponds, open_space):
        before = len(D.out)
        fn(D)
        print('  layer     : %-20s %5d elements' % (fn.__name__, len(D.out) - before))
    sub = enlargement(-80.0, 300.0, -255.0, -35.0, 100.0, 900.0, tag='A')
    for fn in (arcado_row, contours, sewer_existing, existing_structures, boundary):
        fn(sub)
    print('  enlargement: %d elements at 1" = %d\'' % (len(sub.out), round(72.0 / sub.s)))
    svg = finish(D)
    print('  sheet     : %d elements, %d bytes of SVG, disclaimer=%s marker=%s'
          % (len(D.out) - n0, len(svg), DISCLAIMER[:20] in svg, MARKER in svg))
    print('  OK — nothing written.')


if __name__ == '__main__':
    _selfcheck()
