#!/usr/bin/env python3
"""Copy the voluntary-conditions list from docs/02-development-summary.md §9 (the governing text)
into data/voluntary-conditions.md and into docs/03-letter-of-intent.md §11, verbatim.
Re-run whenever the development summary's list changes; tools/check_docs.py flags drift."""
import re, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]
ds = (ROOT / "docs/02-development-summary.md").read_text()
m = re.search(r"^## 9\. Voluntary zoning conditions.*?\n\n(.*?)\n\n---", ds, re.S | re.M)
assert m, "conditions section not found in development summary"
conds = m.group(1).strip()
assert re.match(r"^1\. ", conds) and len(re.findall(r"^\d+\. ", conds, re.M)) >= 10
DISC = ("\n\n> **Disclaimer:** This is an AI-generated analysis for preliminary planning purposes. All findings "
        "must be verified by a licensed professional before use in design, permitting, or regulatory submissions."
        "\n\n<!-- architecture-studio:requires-disclaimer -->\n")
(ROOT / "data/voluntary-conditions.md").write_text(
    "# Voluntary zoning conditions offered with the rezoning application\n\n"
    "Governing text: `docs/02-development-summary.md` section 9. This file is generated by "
    "`tools/sync_conditions.py`; edit the development summary, not this file.\n\n" + conds + DISC)
loi_p = ROOT / "docs/03-letter-of-intent.md"
loi = loi_p.read_text()
pat = re.compile(r"(^## 11\. Voluntary zoning conditions\n\n.*?\n\n)(1\. .*?)(?=\n\n## 12\. )", re.S | re.M)
loi, n = pat.subn(lambda mm: mm.group(1) + conds, loi)
assert n == 1, "LOI §11 list not found"
loi_p.write_text(loi)
print(f"synced {len(re.findall(r'^\d+\. ', conds, re.M))} conditions into data/ and LOI §11")
